import fs from 'node:fs';
const base=JSON.parse(fs.readFileSync(new URL('./base49.json',import.meta.url),'utf8'));
const s=(title,image,steps,takeaway,notes,crop)=>({title,image,steps,takeaway,notes,crop});
const wide=(title,image,takeaway,notes)=>({title,image,wide:true,takeaway,notes});
const t=(title,columns,takeaway,notes)=>({title,kind:'text',columns,takeaway,notes});
const groups={};
groups['Production starts with the plant']=[s('Production dashboard','production-dashboard.png',['Confirm the role and asset scope.','Read availability and loss indicators.','Open the affected plant for the underlying records.'],'The dashboard starts the daily review. Plant records explain the exceptions.','Source: Production dashboard. Use period filters consistently. Dashboard figures are sample data. This view is shown early so users understand how to enter the input workflow.')];
groups['Quality and outages complete the operating picture']=[
s('Outage records and operating impact','production-outages.png',['Open the asset’s Outages tab.','Check full or partial scope and the event window.','Review loss and whether the outage is ongoing.'],'Outage timing can change availability on more than one planning day.','Source: Production Outages screen. Existing Tank Demo Plant A events are used. Confirm local time and day boundaries. This is distinct from planned maintenance.'),
s('Reporting an outage','outage-report-form.png',['Choose the failure type and outage scope.','Enter timing, cause and expected daily loss.','Report the event and update actual loss after it ends.'],'An ongoing outage has no confirmed end time. Update it when recovery is known.','Source: Production Report Outage dialog. The partial-outage form accepts expected losses by day. Actual loss remains disabled until the event end is in the past. The screenshot is an unsubmitted form. No alert was sent for this presentation.',[0.27,0,0.27,0]),
t('Outage notification and planner response',[['Desktop alert','A new-event toast identifies the asset and full or partial outage. Selecting it opens the affected asset’s outage view.'],['Operating review','Inspect the event record, effective capacity and impacted days. Confirm whether the event is still ongoing.'],['Planning response','Update the scenario assumptions, rerun dispatch and review the new shortage before publishing revised decisions.']],'The alert starts the response. The updated run provides the decision evidence.','Source: frontend/src/components/production/OutageNotificationToast.jsx. Desktop polls every 10 seconds, suppresses already-seen IDs and surfaces recent first-load events from the last five minutes. It routes plant, pump and city-gate events to their respective views. No fresh notification was triggered during capture. The portal form promises urgent management notifications, but email recipient coverage and delivery require deployment-specific verification. Do not promise confirmed email delivery in this demonstration.')];
groups['Transmission availability at pump level']=[
s('Transmission dashboard','transmission-dashboard.png',['Review capacity and operating exceptions.','Check the date range and system context.','Continue into systems or individual pump stations.'],'System capacity and pump availability describe different constraints.','Source: Transmission dashboard. Do not add pump capacity to logical line capacity when explaining WTS size.'),
s('Transmission systems in the portal','transmission-systems-list.png',['Open Transmission Systems.','Find the Desktop-authored system.','Select it to review lines and connected assets.'],'The portal provides the operating view of the saved network structure.','Source: Transmission systems list. System A is the saved example. Systems and lines originate in Desktop.'),
wide('The system schematic and line details','transmission-system-detail.png','A system view connects its schematic to registered lines and supplying assets.','Source: Transmission System A detail. Three registered main lines, four saved nodes and three saved pipes. The displayed system aggregate is not proof of end-to-end deliverable flow. Explain source, pump and receiving-gate constraints separately.')];
groups['Economics uses effective cost snapshots']=[s('Economics dashboard','economics-dashboard.png',['Check the operating period and accessible plants.','Review the cost and production context.','Open Financials for the effective cost records.'],'The cost basis must match the dispatch period.','Source: Economics dashboard. Approved production availability depends on account scope and period. Do not infer missing source data solely from an empty dashboard panel.')];
groups['Connections, direction and capacity']=[
s('New assets from the canvas toolbar','canvas-new-asset.png',['Choose Plant, Tank, Pump Station or Handover Point.','Click the intended position on the canvas.','Complete the asset form and add the asset.'],'The quick-add form creates a registry asset as well as placing it on the network.','Source: NetworkEntityCreateModal.jsx and observed Add Plant dialog. Required fields vary by type. The form was opened and cancelled during capture. Use Node for a junction. Creating operational master data requires a valid name, type and specifications.',[0.27,0,0.27,0]),
t('Library placement and drag-and-drop',[['Find an asset','Search by name and filter category or region. Check the registry identity and capacity before placement.'],['Place a group','Select the asset checkboxes and choose Place selected. Click the canvas where the group should appear.'],['Place one asset','Drag the library asset onto the canvas, or select it and place it. Existing canvas assets show an on-canvas state.']],'Library assets preserve the identity needed to read portal inputs.','Source: NetworkPalette and NetworkBuilderPage. The earlier library screenshot shows selection and placement controls. Avoid duplicate registry identities. Positioning changes the drawing, while source records remain in the portals.'),
s('Pipe variables and system creation','canvas-create-system.png',['Choose Pipe, then click source and destination.','Enter capacity, direction and lifecycle dates.','Select a system or name a new system and line.'],'A pipe segment can belong to a named transmission line within a system.','Source: observed Pipeline variables dialog and PipeVariablesModal.jsx. Demonstration System and Main supply line are unsaved form examples. Add pipe creates the new system/line references and adds the connection. Save the network to preserve the reusable geometry. The saved System A shown next illustrates the resulting structure.',[0.27,0,0.27,0]),
t('Main lines and branches',[['System','The named collection used for inspection, reporting and library reuse.'],['Line','A logical line can contain multiple pipe segments. Assign it in the pipe form or element details.'],['Branch','Choose a parent line when creating a branch. Give the branch a meaningful operational name.']],'System, logical line and pipe segment are separate levels of the network.','Source: TransmissionLinePicker.jsx and transmissionLines.js. The Group Lines toolbar command is currently a placeholder. Use the implemented system and line fields in pipe forms instead.'),
s('The saved system in Desktop','desktop-system-detail.png',['Open Transmission, then Transmission Systems.','Select the saved system.','Inspect its network snapshot and line structure.'],'The saved structure supplies the reusable system in the canvas library.','Source: observed Desktop System A. It contains one saved network, three registered lines and three canvas segments. A system name without a saved network bundle does not provide reusable geometry.'),
s('The Systems library','systems-library.png',['Open Library and select Systems.','Search for the required system.','Check saved nodes and saved pipes before placement.'],'Reusable systems bring their saved nodes and connections together.','Source: Desktop Systems library. System A has four saved nodes and three saved pipes. The screenshot shows the library before placement.'),
wide('A complete system placed on the canvas','system-placed.png','Select the system, then click the canvas to place its saved network structure.','Source: live placement of System A into a separate unsaved demonstration network. The action reported four nodes and three pipes and the network rendered after refresh. Review the connections and save under the intended network name. Asset identities remain linked to registered assets.'),
s('Finding an asset on the canvas','canvas-find.png',['Open Find.','Search by name, ID, type or region.','Select a result to focus the matching element.'],'Find searches the current drawing. The library searches available source assets.','Source: observed Qassim City Gate search. To Sel zooms to selected elements. Use Fit to restore the whole-network view.'),
s('Tracing the upstream supply path','canvas-trace.png',['Turn on Trace HP.','Click a city gate or delivery node.','Inspect immediate and ultimate sources.'],'Reachable mode explains topology. Delivered mode needs simulation flow results.','Source: observed Qassim City Gate trace. The example finds Pump Asset 1 as the immediate source and two plants as ultimate sources. A reachable path does not guarantee adequate capacity.'),
s('Isolating systems, lines and assets','canvas-isolation.png',['Open Isolation and find the system or line.','Select a system, line, branch or pipe.','Clear Marks to restore the complete view.'],'Isolation changes what you inspect. It does not shut down the hidden assets.','Source: observed Line A isolation in System A. Isolate / Unisolate also works with a canvas selection. Distinguish visibility filtering from active-state and simulation overrides.'),
s('Pipe bends and route clarity','canvas-bends.png',['Select a pipe to reveal its handles.','Drag a midpoint to create or move a bend.','Remove a bend or use Straighten for all bends.'],'Bends improve schematic readability without changing the pipe’s capacity.','Source: observed midpoint drag and Straighten control, cytoscape/bendEditing.js and NetworkBuilderPage. Double-click an existing bend to remove it. Context actions also add a bend, remove the nearest bend and remove all bends. Recheck direction after editing geometry.'),
s('Alignment, grid and snapping','canvas-align.png',['Select the assets to arrange.','Use alignment or equal-distribution controls.','Enable Grid and Snap for consistent placement.'],'Arrange affects the drawing. Hydraulic capacity and approved records stay separate.','Source: observed toolbar and selected network. Left, Center H, Right, Top, Center V, Bottom, Dist H and Dist V arrange selections. Hold Alt to bypass snapping while moving. Grid, Circle, Tree and Force are alternate layouts. Use Undo if a layout obscures an important route.'),
t('Active assets and disconnected paths',[['Availability','Use element details for asset active state and lifecycle. Activate/Inactive toolbar actions target selected pipes.'],['Diagnosis','Use Disconnected, No Capacity and Inactive review filters. Validate lists errors and warnings with focus controls.'],['Restoration','Fix the missing connection or specification, then validate again. Clear Marks resets selection and review highlights.']],'Visibility, active state and scenario inclusion have different effects.','Source: NetworkBuilderPage and NetworkNodeDetails. Active/Inactive selection tools select matching elements, whereas activation controls change selected pipes. Disconnected finds isolated components. A capacity-free pipe may be treated as unconstrained by dispatch, so inspect its table value before running.'),
s('A schematic reflected on the map','canvas-map.png',['Select an asset with known coordinates.','Pin at least two geographic anchors.','Open Map and inspect the projected network.'],'Anchor accuracy determines the geographic interpretation of the drawing.','Source: observed Map view after pinning Al Amal and Qassim as anchors. Existing registered coordinates avoided manual location entry. Additional unanchored points follow the drawing-to-map transform and are not surveyed positions. Draw route is available in the map view. Return through Schematic.'),
t('KMZ import and geographic review',[['Import','Choose Import and select a KMZ or KML file in a separate network workspace. JSON uses the same import control.'],['Review geometry','Points become classified nodes. Lines become pipes between resolved endpoints, with junctions where needed.'],['Complete the model','Check types and connectivity. Add capacities and source-asset links before using imported geometry for dispatch.']],'A geographic import supplies geometry. It still needs operating specifications.','Source: NetworkBuilderPage buildGeoImportDoc and networkKmz. Imported points become geographic anchors. The browser connection rejected file selection during this capture, so the file-import execution was not verified live. This is a procedure walkthrough, not a successful-import screenshot. Imported geometry does not automatically recreate approved portal identity or every source specification.'),
t('Saving and exporting the network',[['Save and Save As','Save the operational network with a clear name. Save As creates a separate copy for a new scenario.'],['JSON and CSV','JSON exports the canvas document. CSV provides node and edge tables for inspection.'],['KMZ','Set at least two valid geographic anchors, then export KMZ for geographic exchange.']],'Keep the saved network and the exported exchange file identifiable by scenario and date.','Source: NetworkBuilderPage handleSave, handleExportJSON, handleExportCSV, handleExportKMZ. KMZ requires a valid georeference. JSON and KMZ imports replace the current canvas document, so use a new workspace for demonstration. Exports were not opened in external GIS software during this walkthrough.'),
s('Canvas shortcuts and supporting tools','canvas-shortcuts.png',['Use Fit, Area or To Sel to navigate.','Use Undo/Redo and Copy/Paste while editing.','Use network tabs to separate working alternatives.'],'Notes and groups can explain the drawing without becoming supply assets.','Source: observed shortcut guide and toolbar. Additional tools: Labels, minimap, canvas focus mode, category filters, capacity horizon, largest-asset list, Note with font controls, Group, Copy Sel/All, Paste, Edit and Delete. Insert on Pipe places an asset within a connection and splits it. Run/Clear controls show or clear the builder run overlay. The full simulation workflow is in Simulation Config. Group Lines remains a placeholder.')];
groups['What to check before Run simulation']=[
wide('Configuration tables and asset inclusion','simulation-overrides-baseline.png','Each On checkbox controls whether that asset participates in the scenario.','Source: observed Configuration tables. Plant, tank, pump and gate rows offer Include in the dispatch. These are per-scenario assumptions. Pipelines have a separate capacity/direction table. Expand an asset’s daily breakdown to inspect outages and maintenance rather than relying only on the minimum available value.'),
s('Emergency capacity and demand assumptions','simulation-emergency-overrides.png',['Exclude an unavailable asset with its On checkbox.','Enter capacity, cost or demand overrides.','Run again to calculate the changed outcome.'],'This screenshot shows unsaved assumptions. The displayed results still belong to the prior run.','Source: observed unsaved example: Plant A capacity 90,000 m³/day and cost 2.10 SAR/m³, Plant C unchecked, gate demand 280,000 m³/day. All edits were discarded by reloading. No new result is claimed for these settings. Enter a scenario description explaining the emergency and compare a fresh result before publication.'),
t('Storage and throughput during an emergency',[['Tank policy','Set initial, minimum and maximum percentages. Choose the reserve rule appropriate to the tank’s role.'],['Pump throughput','Use the pump capacity override to test a temporary limit. Inspect daily derating and standby coverage.'],['Demand assumption','Test a clearly documented gate demand assumption. Compare delivered volume and shortage after the new run.']],'A capacity or demand override needs a reason, a planning period and a new simulation.','Source: SimulationTables. Tank initial/minimum/maximum overrides and reserve policy differ from the global strategic reserve setting. In the worked scenario the operational tank uses Ignore reserve. A changed cost can alter dispatch order. Configuration edits do not update portal source records.')];
groups['Draft decisions and proposed publication']=[
wide('Binding constraints on the simulation canvas','simulation-bottlenecks.png','The shortage day shows which supplies bind and which gate receives less than requested.','Source: live Simulation Config Canvas on 15 August 2026. Required 300,000 m³, delivered 240,000 m³, shortage 60,000 m³. Plants A and C each bind at 120,000 m³. High utilization and a binding constraint are different signals. Use the legend rather than interpreting every colored pipe as a bottleneck.'),
wide('Tracing delivered water after the run','simulation-delivered-trace.png','Delivered trace follows the selected day’s contributing flows to the receiving gate.','Source: live selected Tank Demo City Gate trace. Immediate source is Tank Demo Pump Station with 240,000 m³. Four upstream nodes contribute. The side panel and element history help connect a local shortfall to daily operation.'),
t('Simulation canvas review tools',[['Time controls','Select an individual day, use Previous/Next, or play the horizon. Compare shortage days with fully served days.'],['Network overlays','Toggle Flow, Legend and Bottlenecks. Select an element to inspect its daily operating history.'],['Focused review','Use Trace and Isolate to inspect a path. Fit, Reset and Clear restore a broader view.']],'The simulation canvas explains the saved run. Edit the model or assumptions before rerunning.','Source: observed Simulation Canvas and CanvasToolbar. The canvas is a result-inspection surface. Use Configuration for scenario overrides and Network Builder for topology changes. Keep the selected run and day visible when discussing decisions.')];
let out=[];
for(const d of base){
 if(d.title==='The planner’s data-readiness check')continue;
 if(d.title==='Economics reviews the operating outcome')continue;
 if(d.title==='The next operating cycle') {out.push(t('The next operating cycle',[['Published plan','Operators receive the approved allocation and applicable decisions.'],['Actual outcome','Teams enter actual production, receipts and delivery against the same date and asset.'],['Next review','Use variance, outages and approval history to prepare the next scenario.']],'Publication completes a planning cycle. Reconciliation begins the next one.',d.notes));continue;}
 if(groups[d.title])out.push(...groups[d.title]);
 if(d.kind==='agenda'){d.rows=[['01','Assets, portal dashboards, inputs and approvals','15 minutes'],['02','Network and transmission system walkthrough','12 minutes'],['03','Emergency assumptions and simulation results','10 minutes'],['04','Decisions, publication and portal reconciliation','10 minutes'],['05','Optional canvas tools and geographic detail','20–30 min']];d.notes='Core client walkthrough: approximately 45–50 minutes using selected canvas slides. The extended canvas and outage material supports a longer workshop or follow-up questions. Do not read every reference slide in the core session.';}
 if(d.kind==='cover')d.notes='Operational-user and approver demonstration. Use a 45–50 minute core path and optional detailed canvas sections for a longer workshop. Screenshots contain sample records from multiple dates. The worked shortage case uses the saved Tank Demo run.';
 out.push(d);
}
for (const d of out) { if(d.image==='canvas-new-asset.png') d.crop=[0.30,0.04,0.30,0.35]; if(d.image==='canvas-create-system.png')d.crop=[0.30,0.04,0.30,0.08]; }
export const slides=out;
