export const asOf='29 September 2026';
export const sources={
 D1:'Desktop/backend/src/server.js:31-64 and API routes; Desktop/frontend/src/api/client.js:1-20; package.json in frontend and backend',
 D2:'Desktop/backend/src/db.js:9-28; Production/Demand lib/mongodb.ts:38-41; Transmission/Economics lib/mongodb.ts:38-43; Production/Transmission/Economics app/api/users/assign/route.ts:33',
 D3:'Desktop/backend/src/simulationConfigs.js:38-84, 176-255',
 D4:'Desktop/backend/src/simulation/writeback.js:23-130',
 D5:'Desktop/backend/src/simulation/dispatch.js:101-145, 178 onward; capacity.js; cost.js:16-67; graph.js; mcmf.js',
 D6:'Desktop/backend/src/assetRegistry.js:12-23, 221-335; networks.js; transmissionRegistry.js',
 P1:'Production, Demand, Transmission, Economics: lib/rbac.ts and lib/types.ts (current working files)',
 P2:'All four portals: lib/auth.ts and app/api/auth/login/route.ts:13-49',
 P3:'All four portals: app/api/submissions/[id]/status/route.ts (role gate, record lookup, status update and audit)',
 P4:'Production components/production/production-input-table.tsx:171-185; Demand equivalent:183-198',
 P5:'Production lib/email.ts:7-13, 35-201; other portals lib/email.ts; app/api/test-email/route.ts',
 P6:'Production, Demand, Transmission lib/imports.ts; shared excel-import-dialog components',
 P7:'Production app/api/audit-logs/route.ts; submissions/[id]/status/route.ts:175 onward; lib/rbac.ts audit helpers',
 P8:'Economics app/api/financial-entries/route.ts; lib/financial-costs.ts; Desktop simulation/cost.js',
 G1:'Desktop/frontend/src/pages/NetworkBuilderPage.jsx:2896-2905, 3122-3180, 3575-3578; lib/networkKmz.js; components/networkCanvas/NetworkCanvasMapView.jsx:101; AssetDetailPage.jsx:174',
 T1:'Desktop backend existing test suite, executed 2026-09-29 with Node --test: 87 tests, 87 passed, 0 failed, 0 skipped; local runner duration 564.0742 ms. Private execution log retained.',
 R1:'WIDispatch_SRD.docx, internal draft v1.0, 10 September 2026: sections 1, 5, 6 and 7. Proposed requirements and trial targets, not deployment evidence.',
 S1:'Source inventory of app/lib/backend/frontend and package manifests in the five supplied repositories, 2026-09-29. Targeted search only, not an exhaustive security or integration audit.'
};
export const ref=(ids)=>ids.split(',').map(id=>`[${id}] ${sources[id.trim()]}`).join('\n');
export const roles=[
 ['GM / Head','Entity/global*','Yes, scoped','Yes','All role types*','Yes, hierarchy','P1,P3'],
 ['Regional Head','Assigned region','Yes, scoped','No','City / asset / read-only','Yes, hierarchy','P1'],
 ['City / Governorate Head','Assigned city/governorate','Yes, scoped','No','Asset manager / read-only','Yes, hierarchy','P1'],
 ['Asset manager (plant_manager)','Assigned plants/city gates*','Yes, scoped','No','No','No','P1'],
 ['Read-only stakeholder','Assigned scope*','No','No','No','No','P1'],
 ['Dashboard Approver','Approvals view; no direct asset scope','No','Yes','No','No','P1,P3']
];
export const roleExceptions=[
 ['Production GM','Entity restriction applies when scope.entity is set. Without it the helper returns all plants.','Current source','P1'],
 ['Demand / Transmission / Economics GM','The inspected getAccessiblePlants helper returns all plants. Do not describe identical entity isolation across portals.','Current source','P1'],
 ['Transmission / Economics non-plant assets','getAccessibleAssets can return all assets for plant_manager/read_only when no region/city scope is set. Assignment-level isolation needs endpoint verification.','Current source','P1'],
 ['Approval API boundary','Role gate exists. The inspected status routes retrieve records by ID without an asset-scope check or a distinct-submitter check.','Development required','P3'],
 ['User creation','GM helper permits any target role, but getAllowedRolesToCreate omits dashboard_approval. Confirm provisioning path and endpoint checks.','Validation required','P1'],
 ['Desktop planner / publisher','Planning functions exist, but the inspected Express API does not authenticate callers or enforce role-based permissions. Planner/publisher separation is proposed.','Development required','D1,D3'],
 ['Platform administrator','Hosting, backup and database administration are deployment responsibilities. Portal GM is not a server administrator role.','Responsibility to agree','R1']
];
export const ownership=[
 ['Assets and identifiers','Asset steward via Desktop registry','plants, pumps, cityGates, tanks and other asset collections','All applications reference stable IDs; display names are not identifiers.','Portal asset routes also exist. Agree one steward and protect referenced deletions.','D6'],
 ['Network topology and systems','Dispatch planner via Desktop','networks, transmissionSystems, transmissionLines','Simulation uses saved graph; Transmission displays Desktop-authored systems/lines.','Saving a network/system is separate from publishing a dispatch plan.','D6'],
 ['Production operating records','Production team','productionInputs; qualityRecords; contractedCapacity','Actual production and available-capacity context support planning/reconciliation.','Publish owns required_m3 planning allocation; actual values remain operational input.','D4,P4'],
 ['Demand and actual receipts','Demand team','demandInputs, keyed by plant_id for a city gate and date','Approved required demand feeds the run; received_m3 records actual receipts.','required_m3, desktop_approved_m3 and received_m3 have different meanings.','D4,D5,P4'],
 ['Maintenance and outages','Relevant asset operations team','maintenanceRecords and outages','Availability uses eligible maintenance and approved outages.','Maintenance eligibility is not identical to demand approval. Dates are not rescheduled by publication.','D4,D5'],
 ['Transmission water movement','Transmission team','receivedRecords and deliveredRecords','Operational receipt/delivery reconciliation.','Dispatch publication does not write these actual movement records.','D4,R1'],
 ['Cost assumptions','Economics team and approvers','financialEntries; asset specifications as fallback','Latest applicable approved plant variable O&M sets dispatch cost.','Fallback to plant specification, then 2.10 SAR/m3. Agree fallback policy.','D5,P8'],
 ['Scenario configuration','Dispatch planner','simulationConfigs','Network, dates, overrides and storage policy define a run.','Run-only overrides can differ from saved settings.','D3'],
 ['Results and reviewed decisions','Dispatch planner; publisher role proposed','dispatchPlans','Run creates a draft. Supported decision edits precede explicit publication.','Manual decision patches do not recalculate hydraulic/network flow or plant allocations.','D3,D4'],
 ['Identity and audit records','Application administrator / security owner','users, auditLogs and notifications','Portal login, scope, approval history and notifications.','Unified identity lifecycle, immutable audit retention and complete Desktop actor logging need work.','P1,P2,P3,P7']
];
export const publication=[
 ['Production allocation','plantAllocations -> productionInputs','plant_id + date; upsert','required_m3; data_source=desktop_simulation; decision status; dispatch_plan_id','Preserves existing actual/approval fields. New row starts draft.','Production requested allocation uses required_m3.','D4,P4'],
 ['Demand decision','demandVerdicts -> demandInputs','plant_id + date; update only','desktop_approved_m3; decision/recommendation/status/comment fields; plan ID','Does not replace required_m3 or actual receipts. Missing target is not inserted.','Inspected daily table does not use desktop_approved_m3. Review in Desktop until UI mapping is validated.','D4,P4'],
 ['Maintenance decision','maintenanceVerdicts -> maintenanceRecords','record id or ObjectId; update only','desktop_approval_status; decision/recommendation/comments; approved timestamp; plan ID','Does not rewrite maintenance start/end dates or portal submission status.','Desktop approval metadata is available to consuming views; validate each portal surface.','D4'],
 ['Plan publication state','dispatchPlans','plan id','status=published; publishedAt; publishedCounts','Marked after the three collection writes complete.','Sequential repeat on a published plan is rejected; simultaneous publication is not locked.','D3,D4'],
 ['Transmission actuals','No dispatch write','Not applicable','No receipt/delivery actual writes','receivedRecords and deliveredRecords stay operationally owned.','Systems display follows saved registry/network data, not dispatch publication.','D4,D6'],
 ['Economics costs','No dispatch write','Not applicable','No financialEntries writes','Approved economic snapshots remain unchanged.','Financial dashboards may read operating data; publishing is not cost approval.','D4,P8']
];
export const integrations=[
 ['Internal operational data','Portal services and Desktop API read/write MongoDB collections','Current capability','Shared collection contract in source','Reconcile database selection and schema ownership. Cross-app fixture required.','Engineering / DBA','D2,D4,D5'],
 ['Desktop frontend / REST API','Browser JSON requests to configured API base URL','Current capability','Fetch-based client and Express routes','Secure endpoint, CORS allowlist, versioned contract and API documentation required.','Engineering / IT','D1'],
 ['Spreadsheet import and export','User-triggered file exchange in supported portal screens','Current capability','Import mappings and dialogs in source','Validate required modules, templates, large files and rejection messages.','Operations / QA','P6'],
 ['GIS / network file exchange','Canvas JSON, KMZ/KML import; JSON/CSV/KMZ export','Current capability','Import/export handlers in source','File exchange is not live enterprise GIS synchronisation. Acceptance test geometry/asset mapping.','GIS owner / QA','G1'],
 ['External map tiles','Browser requests OpenStreetMap / ArcGIS imagery','Configuration required','Tile URLs in source','Client must approve internet egress/provider terms or commission an internal/offline map source.','IT / GIS','G1'],
 ['Email notifications','Console default; SMTP / SendGrid / SES adapter paths','Configuration required','Provider code exists; delivery not tested here','Configure approved sender/recipients, optional dependencies and transport. Test delivery and failure.','IT / Engineering','P5'],
 ['Corporate SSO and MFA','Identity-provider integration to be designed','Development required','Inspected login uses local passwords and JWT','Agree OIDC/SAML provider, group-to-role mapping, logout/revocation and MFA policy.','Identity team / Engineering','P2,S1'],
 ['ERP / EAM / CMMS','External asset, maintenance or cost exchange','Development required','No implementation identified in inspected app/lib paths','Agree systems, IDs, direction, schedule, error handling and interface ownership.','Client system owners','S1'],
 ['SCADA / historian','Operational measurements into planning','Development required','No telemetry connector identified in inspected application paths','Agree read-only ingestion, time aggregation, units and quality flags.','OT team / Engineering','S1'],
 ['Equipment control','Commands to pumps/valves','Development required','No equipment-control connector identified','Separate scope and control/safety design. Do not equate Publish with actuator commands.','OT / Product','D4,S1'],
 ['SIEM / central monitoring','Security and service events to client tooling','Configuration required','Console and portal audit paths exist; connector not evidenced','Agree event schema and collector. Application changes may be needed for full actor/context coverage.','Security / Operations','D1,P7,R1']
];
export const evidence=[
 ['E01','Portal authentication','Source inspected','Password comparison with bcrypt and signed JWT login; seven-day token setting.','No authenticated penetration or session-revocation test in this review.','Test invalid/expired tokens, revocation and approved session policy.','P2'],
 ['E02','Portal role and scope','Source inspected; gaps identified','Six role codes and scope helpers exist. Approval routes have role checks.','Inspected approval status routes do not check record asset scope or separate submitter/approver.','Implement and test cross-scope denial and separation of duties.','P1,P3'],
 ['E03','Desktop authentication','Source inspected; gap identified','Express routes and frontend requests inspected. No authentication middleware found in server.js.','A protected reverse proxy, if any, was not inspected and would not prove per-action RBAC.','Enforce identity and scoped authorization on protected APIs.','D1'],
 ['E04','Secrets / diagnostics / CORS','Source inspected; gaps identified','Portal signing-secret fallback, Desktop unrestricted cors(), and diagnostic email route identified.','No secret values or live environment settings inspected. No request sent to email endpoints.','Remove fallback, fail closed, restrict origins and protect/disable diagnostics.','D1,P2,P5'],
 ['E05','Audit and lineage','Source inspected','Portal approval actor/time audit writes and dispatch_plan_id lineage exist.','No immutable retention or complete authenticated Desktop publication audit established.','Define actor events, protected retention and SIEM export.','P3,P7,D4'],
 ['E06','Publication atomicity','Source inspected; gap identified','Three unordered bulk writes run in parallel, followed by plan status update.','No transaction, request idempotency key or versioned input check in inspected path.','Fault-injection, retry, simultaneous publish and stale-input tests after implementation.','D3,D4'],
 ['E07','Decision editing','Source inspected and unit tested','Bounds 0..required, revision/rejection comments, and published-plan edit guard exist.','Decision patches do not re-solve supply/flow. No revision compare-and-set across draft editors.','Revalidate edits against feasible allocations and add version checks.','D3,T1'],
 ['E08','Backend functional tests','Executed 2026-09-29','87 tests passed; 0 failed; 0 skipped. Covers solver, capacity, storage, cost and decision helpers.','Local unit/fixture execution, not live database or five-app acceptance. Runner duration is not simulation SLA.','Retain this baseline and add deployment integration tests.','T1'],
 ['E09','Production performance','Not measured','No controlled target-host load benchmark performed.','SRD trial envelope and response targets are proposals only.','Agree users, graph size, horizon and dataset. Measure p95 API time, run time and memory.','R1,S1'],
 ['E10','Backup and restore','Not verified','No backup configuration or restoration exercise inspected.','SRD proposes RPO <=24h, RTO <=8h and 14-day trial retention; not an SLA.','Agree production targets and restore into an isolated environment.','R1'],
 ['E11','Availability and failover','Not verified','No deployed HA/failover evidence supplied in this review.','A proposed single VM or single-node replica set does not demonstrate high availability.','Choose topology and test service/database failure behaviour.','R1'],
 ['E12','Transport / at-rest encryption','Deployment evidence absent','Application/database client code is available for inspection.','No certificates, reverse proxy, database encryption, key custody or hosting region verified.','Provide configuration evidence and connection/restore tests on approved host.','D1,D2,R1'],
 ['E13','Penetration / vulnerability testing','Evidence absent','No penetration-test report or complete dependency-security assessment reviewed.','Source inspection and unit tests cannot certify security or compliance.','Agree assessment scope, remediate findings and retest.','S1,R1'],
 ['E14','Release / rollback','Source inspected; deployment unverified','Build scripts exist; Production next.config.mjs ignores TypeScript build errors.','No validated release pipeline, migration rollback or recovery rehearsal shown.','Run explicit type checks, record revisions, back up and rehearse compatible rollback.','R1,S1'],
 ['E15','Database consistency','Source inspected; gap identified','Production/Demand use fixed DB name; Desktop/Transmission/Economics derive from URI. Assignment routes in three portals use another fixed name.','Live connection strings intentionally not read. Actual data isolation is not proven.','Unify environment DB policy and test account assignment plus cross-app fixtures.','D2'],
 ['E16','Client environment acceptance','Not performed','Previous demonstration screenshots are available as workflow illustrations.','Screenshots do not establish security, load, recovery or current client-environment acceptance.','Run role-by-role UAT and full input-to-publication reconciliation on client-approved test data.','R1']
];
// Register categories describe implementation work. Evidence status is independent.
export const register=[
 ['C01','Current capability','Core workflow','Portal inputs and approval','Role helpers and submission routes exist.','Complete module/role acceptance.','QA / Operations','Representative input, approval and rejection succeed in correct scope.','P1,P3'],
 ['C02','Current capability','Core workflow','Asset registry and network','Registry, graph and transmission system routes exist.','Agree stewardship and test save/reload.','Asset steward / QA','Stable asset IDs and saved topology reconcile across views.','D6'],
 ['C03','Current capability','Core workflow','Dispatch calculation','Daily sequential min-cost maximum-flow subproblems with storage carryover.','Validate client scenarios and operational assumptions.','Planning / QA','Known shortage, bottleneck, outage and storage fixtures meet expected outcomes.','D5,T1'],
 ['C04','Current capability','Core workflow','Decision review and comments','Supported demand/maintenance patches and comments exist.','Demonstrate existing bounds; explain feasibility limitation.','Planning / QA','Invalid quantities and missing required comments are rejected.','D3,T1'],
 ['C05','Current capability','Core workflow','Explicit publication','Production/demand/maintenance writeback and plan lineage exist.','Reconcile target fields in each portal.','Engineering / QA','Expected records and fields match the published plan.','D4'],
 ['C06','Current capability','Core workflow','File exchange','Spreadsheet and canvas GIS/file handlers exist.','Test agreed files and mapping.','GIS / Operations','Accepted files round-trip with expected IDs, units and geometry.','G1,P6'],
 ['C07','Current capability','Core workflow','Backend test baseline','87 existing tests pass in local execution.','Retain test log and add missing integration scenarios.','Engineering / QA','Regression suite remains passing on release revision.','T1'],
 ['F01','Configuration required','Before client deployment','Hosting and residency','No approved client deployment inspected.','Agree region, hosting owner, domains and isolated environments.','Client IT / Service owner','Approved deployment record and environment boundaries.','R1'],
 ['F02','Configuration required','Before client deployment','HTTPS and private database','Transport/network controls are deployment-dependent.','Configure certificates, private DB access and least-privilege accounts.','IT / DBA','Approved HTTPS entry points work; public DB/admin access denied.','D1,D2,R1'],
 ['F03','Configuration required','Before client deployment','Identity scope and provisioning','Portal scopes exist but vary by app/asset type.','Agree role assignments and offboarding policy after API gaps close.','Identity / Business owner','Role matrix and access/revocation acceptance signed off.','P1,P2'],
 ['F04','Configuration required','Before client deployment','Email delivery','Provider adapters exist; console is default.','Configure sender/provider/recipients and confirm dependencies.','IT / Engineering','Submission and approval messages deliver to approved recipients.','P5'],
 ['F05','Configuration required','Before client deployment','Map connectivity','External map tile URLs exist.','Approve outbound hosts or scope an internal map alternative.','IT / GIS','Maps load under agreed network policy.','G1'],
 ['F06','Configuration required','Before client deployment','Backups and restore','No operational recovery evidence reviewed.','Agree RPO/RTO/retention, configure jobs and rehearse restore.','Operations / DBA','Measured isolated restore meets agreed targets with retained plan checks.','R1'],
 ['F07','Configuration required','Before client deployment','Monitoring and support','Service health route exists; operations arrangement unverified.','Agree alerts, escalation, support hours and responsibility matrix.','Service owner / Client IT','Failure alert and escalation exercise completes.','D1,R1'],
 ['F08','Configuration required','Before client deployment','Performance acceptance','No measured client-host capacity established.','Agree workload and execute controlled load tests.','QA / IT','Measured API and run timings meet agreed targets.','R1,T1'],
 ['F09','Configuration required','Before client deployment','Cost fallback policy','Approved Economics value, plant spec, then default 2.10 SAR/m3.','Agree whether fallback may be used and how users approve it.','Finance / Planning','Missing-cost scenario clearly flags source and follows approved policy.','D5'],
 ['F10','Configuration required','Before client deployment','Retention and data exit','Commercial and operational terms need agreement.','Define records retained, export formats, disposal and access termination.','Data owner / Service owner','Approved data-exit sample and retention schedule.','R1'],
 ['D01','Development required','Before production use','Desktop authentication and RBAC','No authenticated/scoped API boundary in inspected server.','Implement verified identity, scope and action checks.','Engineering / Security','Anonymous and cross-scope calls fail; valid roles can perform allowed actions.','D1'],
 ['D02','Development required','Before production use','Portal approval scope and duties','Role check does not establish record-level scope or maker/checker separation.','Add scope and distinct-actor policy enforcement.','Engineering / Security','Cross-scope and prohibited self-approval tests reject without mutation.','P3'],
 ['D03','Development required','Before production use','Authoritative database configuration','Selection differs across apps and assignment routes.','Use validated environment-specific DB configuration consistently.','Engineering / DBA','All five apps plus user assignment read the intended isolated dataset.','D2'],
 ['D04','Development required','Before production use','Atomic publication and retries','Parallel bulk writes without a transaction or idempotency key.','Add transactional publication and safe retry identity.','Engineering / DBA','Injected failure rolls back; repeated/concurrent request commits once.','D4'],
 ['D05','Development required','Before production use','Draft concurrency and input versions','Draft status guard exists; no revision token or immutable input-version check.','Add compare-and-set revisions and input snapshot/version validation.','Engineering','Stale edits conflict; changed planning inputs require revalidation.','D3,D4'],
 ['D06','Development required','Before production use','Manual edit feasibility','Patches change decisions without recalculating allocation/flow.','Define approved edit policy and re-solve/revalidate affected plan.','Planning / Engineering','Edited demand remains consistent with feasible supply, network flow and output allocations.','D3,D4'],
 ['D07','Development required','Before production use','Publication completeness','Modified/upsert counts do not prove every target matched.','Check expected/matched records and block incomplete publication.','Engineering','Missing demand/maintenance target fails safely with a clear reason.','D4'],
 ['D08','Development required','Before production use','Authenticated audit and retention','Portal audit and plan IDs exist; complete Desktop actor trail absent.','Record actor, revision, input basis, outcome and request identity; protect retention.','Engineering / Security','Publication and overrides trace to authenticated actors and immutable evidence.','D1,P7,D4'],
 ['D09','Development required','Before production use','Secrets, CORS and diagnostics','Fallback signing key, open CORS and diagnostic email route identified.','Remove insecure defaults; require secrets; restrict origins and diagnostics.','Engineering / Security','Missing secrets fail startup; unapproved origins/diagnostics are denied.','D1,P2,P5'],
 ['D10','Development required','If client requires','Corporate SSO / MFA','Local password/JWT login observed; enterprise federation not identified.','Integrate approved IdP and map groups to roles/scopes.','Identity / Engineering','SSO, MFA policy, session revocation and offboarding pass UAT.','P2,S1'],
 ['D11','Development required','If client requires','ERP / EAM / historian connectors','No connector implementation identified in inspected app/lib paths.','Define interface contract then develop and test adapters.','System owners / Engineering','Mapped data exchange handles duplicates, failures and reconciliation.','S1'],
 ['D12','Development required','Before production use','Demand decision display','Inspected daily table uses required_m3 and received_m3, not desktop_approved_m3.','Expose allocated decision/comment/plan lineage consistently if required by workflow.','Product / Engineering','Published allocation and rationale are visible at the agreed receiving-point screen.','P4,D4'],
 ['D13','Development required','Before production use','Referenced asset deletion','Registry delete path does not check retained network/plan references.','Protect referenced assets or implement approved archival rules.','Engineering / Data owner','Deleting a referenced asset cannot orphan a retained network/plan.','D6'],
 ['D14','Development required','Before production use','Legacy decision paths','Per-row Desktop approval endpoints coexist with plan publication.','Apply identical permissions and lineage rules or disable conflicting paths.','Engineering','All decision writes obey the same approved policy.','D1,D4'],
 ['D15','Development required','Before production use','Release quality gates','Build scripts exist; ignored type errors observed in Production config.','Require explicit type checks/tests and reproducible release evidence.','Engineering / Release owner','Recorded release passes gates and rollback rehearsal.','R1,S1']
];
export const deployment=[
 ['Browser access','Current: React interfaces for all five applications','Client endpoint team','Supported browser/device versions and network route','Browser smoke test and role login','D1,P2'],
 ['Desktop delivery','Current: React/Vite browser frontend plus Express API','Application owner','Serve compiled frontend; configure API URL','No installed Windows executable assumed','D1'],
 ['Portal services','Current: four Next.js servers with API routes','Application owner','Separate service/process configuration and approved HTTPS routes','Each service health and functional smoke test','D1,S1'],
 ['Database','Current: MongoDB-backed operational/planning collections','DBA / Engineering','Private access, consistent environment DB name, scoped credentials','Cross-app fixture and assignment test','D2'],
 ['Proposed ingress','HTTPS reverse proxy/load balancer','Client IT / Hosting owner','DNS, certificates, firewall and private application ports','External scan and certificate validation','R1'],
 ['Proposed trial host','SRD proposal: Linux VM, 4 vCPU, 16 GB RAM, about 100 GB storage','Hosting owner','Sizing subject to measured workload; not a production recommendation','Agreed load benchmark on chosen host','R1'],
 ['Production availability','Design decision pending','Client IT / Service owner','Redundancy, maintenance window, DB topology and failover','Recovery and failure tests','R1'],
 ['Backup / recovery','Configuration and evidence pending','Operations / DBA','Retention, backup location, encryption, key access, RPO/RTO','Isolated restoration with records and saved-plan checks','R1'],
 ['External services','Map tiles and optional email','Client IT / Security','Allowlist approved services or design alternatives','Egress and mail-delivery checks','G1,P5'],
 ['Identity federation','Development scope if required','Client identity team / Engineering','IdP, protocol, claims, role mapping and deprovisioning','SSO/MFA/revocation acceptance','P2,S1'],
 ['Operational handover','Responsibilities and terms pending','Service owner / Client IT','Monitoring, patching, incident response, release and rollback ownership','Signed responsibility matrix and runbooks','R1']
];
export const answers=[
 ['What is Desktop?','The inspected Desktop is a browser-based planning application built with React/Vite and an Express API. It is not an installed Windows package in this source.','Confirm the intended client delivery and supported browsers.','D1'],
 ['Where will it run?','The application can be packaged for an agreed hosted environment. Our deployment diagram is a proposal; the hosting region, operator and production topology need agreement.','Ask for hosting, residency and network requirements.','R1'],
 ['Can we use corporate login?','The current portal login uses local accounts and JWT. Corporate SSO/MFA integration is a defined development and acceptance item. Desktop API access control also needs implementation.','Do not describe SSO or uniform five-app RBAC as already delivered.','P2,D1'],
 ['How is access controlled?','Portal role and scope helpers exist. We have documented their matrix and identified approval-scope and separation-of-duty gaps for closure.','Agree approver scope and whether self-approval is prohibited.','P1,P3'],
 ['How do the applications share data?','They use MongoDB-backed services and common asset references. We need to reconcile environment database selection before deployment.','Confirm the authoritative asset owner and environment data boundaries.','D2,D4,D5'],
 ['What does simulation optimise?','It uses daily sequential flow calculations to allocate feasible supply with variable operating cost and storage policy. It is not evidence of pressure/head-loss hydraulic simulation or globally optimal multi-period scheduling.','Use shortage, bottleneck and storage fixtures to explain behaviour.','D5,T1'],
 ['Can a user change a decision?','Supported edits have quantity bounds and comment rules. Currently they do not recalculate network flows or plant allocations, so a feasibility revalidation policy is required.','Do not demonstrate a quantity override as a physically re-optimised result.','D3,D4'],
 ['What happens on Publish?','It writes production allocations and demand/maintenance decision metadata. It preserves portal approval state and actual operating values. Transactional failure recovery is a development item.','Show the exact field mapping; avoid assuming every portal displays every field.','D4,P4'],
 ['What integrations exist?','Internal data sharing, file exchange, map services and email adapter paths exist. ERP, corporate identity and telemetry connectors need specific scope and implementation.','Ask for system names, data direction, frequency, units and owner.','G1,P5,P6,S1'],
 ['What evidence can you show?','We reran 87 existing backend tests successfully. We have not established client-host load capacity, penetration-test results or measured restore targets in this review.','Agree the acceptance evidence and owners before production approval.','T1,R1']
];
